# Cloudflare Pages 빌드 설정
name = "web-util"
pages_build_output_dir = ".output/public"

[build]
command = "pnpm install && pnpm build:cloudflare"
cwd = ""
ignore = ""

[build.environment]
NODE_VERSION = "20.19.4"
PNPM_VERSION = "9"

# 환경 변수 설정
[vars]
NUXT_PUBLIC_SITE_URL = "https://web-util.pages.dev"

# Functions 설정 (필요시)
[[functions]]
pattern = "/api/*"
script = ".output/server/index.mjs"

# 리다이렉트 설정
[[redirects]]
from = "/assets/*"
to = "/:splat"
status = 301

# 헤더 설정
[[headers]]
for = "/_nuxt/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/css/*"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"